// app/layout.js (or layout.tsx) - Modified

import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/navbar'; // <-- Import Navbar
import Footer from './components/footer'; // <-- Import Footer
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App", // Update with your actual title
  description: "Generated by create next app", // Update description
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-black text-white`} // Added font-sans, bg-black, text-white
      >
        <div className="min-h-screen flex flex-col relative">
          <Navbar /> 
          <main className="flex-grow">
            {children}
          </main>
          <Footer /> 
        </div>
      </body>
    </html>
  );
}